import prisma from '@/lib/db'
import React from 'react'

const page = async() => {

// const teacherData = [
//   {
//     id: '1',
//     firstName: 'Abdullateef',
//     lastName:'Yunus',
//     username:'Yunus',
//     email: 'yunus@gmail.com',
//     phone: '+2348012345671',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/1.jpg',
//   },
//   {
//     id: '2',
//     firstName: 'Bello',
//     lastName:'Amina',
//     username:'Amina',
//     email: 'amina@gmail.com',
//     phone: '+2348012345672',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/2.jpg',
//   },
//   {
//     id: '3',
//     firstName: 'Okoye',
//     lastName:'David',
//     username:'David',
//     email: 'david@gmail.com',
//     phone: '+2348012345673',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/3.jpg',
//   },
//   {
//     id: '4',
//     firstName: 'Sule',
//     lastName:'Fatima',
//     username:'Fatima',
//     email: 'fatima@gmail.com',
//     phone: '+2348012345674',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/4.jpg',
//   },
//   {
//     id: '5',
//     firstName: 'Johnson',
//     lastName:'Michael',
//     username:'Michael',
//     email: 'michael@gmail.com',
//     phone: '+447911234561',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/5.jpg',
//   },
//   {
//     id: '6',
//     firstName: 'Musa',
//     lastName:'Zainab',
//     username:'Zainab',
//     email: 'zainab@gmail.com',
//     phone: '+2348012345676',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/6.jpg',
//   },
//   {
//     id: '7',
//     firstName: 'Brown',
//     lastName:'Joseph',
//     username:'Joseph',
//     email: 'joseph@gmail.com',
//     phone: '+14161234567',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/7.jpg',
//   },
//   {
//     id: '8',
//     firstName: 'Danjuma',
//     lastName:'Halima',
//     username:'Halima',
//     email: 'halima@gmail.com',
//     phone: '+2348012345678',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/8.jpg',
//   },
//   {
//     id: '9',
//     firstName: 'Ade',
//     lastName:'Samuel',
//     username:'Samuel',
//     email: 'samuel@gmail.com',
//     phone: '+2348012345679',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/9.jpg',
//   },
//   {
//     id: '10',
//     firstName: 'Williams',
//     lastName:'Grace',
//     username:'Grace',
//     email: 'grace@gmail.com',
//     phone: '+2348012345680',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/10.jpg',
//   },
//   {
//     id: '11',
//     firstName: 'Lawal',
//     lastName:'Ibrahim',
//     username:'Ibrahim',
//     email: 'ibrahim@gmail.com',
//     phone: '+2348012345681',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/11.jpg',
//   },
//   {
//     id: '12',
//     firstName: 'Martins',
//     lastName:'Rita',
//     username:'Rita',
//     email: 'rita@gmail.com',
//     phone: '+2348012345682',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/12.jpg',
//   },
//   {
//     id: '13',
//     firstName: 'Kareem',
//     lastName:'Abdul',
//     username:'Abdul',
//     email: 'abdul@gmail.com',
//     phone: '+2348012345683',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/13.jpg',
//   },
//   {
//     id: '14',
//     firstName: 'Cole',
//     lastName:'Janet',
//     username:'Janet',
//     email: 'janet@gmail.com',
//     phone: '+2348012345684',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/14.jpg',
//   },
//   {
//     id: '15',
//     firstName: 'Sadiq',
//     lastName:'Musa',
//     username:'Musa',
//     email: 'musa@gmail.com',
//     phone: '+2348012345685',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/15.jpg',
//   },
//   {
//     id: '16',
//     firstName: 'Park',
//     lastName:'Linda',
//     username:'Linda',
//     email: 'linda@gmail.com',
//     phone: '+821012345678',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/16.jpg',
//   },
//   {
//     id: '17',
//     firstName: 'Adebayo',
//     lastName:'Sola',
//     username:'Sola',
//     email: 'sola@gmail.com',
//     phone: '+2348012345687',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/17.jpg',
//   },
//   {
//     id: '18',
//     firstName: 'Thompson',
//     lastName:'Mary',
//     username:'Mary',
//     email: 'mary@gmail.com',
//     phone: '+447911234568',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/18.jpg',
//   },
//   {
//     id: '19',
//     firstName: 'Abdullahi',
//     lastName:'Umar',
//     username:'Umar',
//     email: 'umar@gmail.com',
//     phone: '+2348012345689',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/men/19.jpg',
//   },
//   {
//     id: '20',
//     firstName: 'Young',
//     lastName:'Patricia',
//     username:'Patricia',
//     email: 'patricia@gmail.com',
//     phone: '+12125551234',
//     bloodType:'A',
//     sex:'MALE',
//     img: 'https://randomuser.me/api/portraits/women/20.jpg',
//   },
// ];

// const teachers = await prisma.teacher.createMany({
//     data:teacherData
// })
//     const users = await prisma.student.createMany({
//         data:[
//   {
//     id: '1',
//     firstName:'Yunus',
//     lastName:'Fatai',
//     username :'yunus',
//      email: 'yunus@gmail.com',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/1.jpg',
//     phone: '123455678909',
//   },
//   {
//     id: '2',
//     firstName:'Aisha',
//     lastName:'Bello',
//     email: 'aisha@gmail.com',
//     username:'aisha',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/2.jpg',
//     phone: '123455678910',
//   },
//   {
//     id: '3',
//     firstName:'Daniel',
//     lastName:'fatai ',
//     email: 'daniel@gmail.com',
//     username:'daniel',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/3.jpg',
//     phone: '123455678911',
//   },
//   {
//     id: '4',
//     firstName:'Fatima',
//     lastName:'fatai ',
//     email: 'fatima@gmail.com',
//     username:'fatima',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/4.jpg',
//     phone: '123455678912',
//   },
//   {
//     id: '5',
//     firstName:'Michael',
//     lastName:'fatai ',
//     email: 'michael@gmail.com',
//     username:'michael',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/5.jpg',
//     phone: '123455678913',
//   },
//   {
//     id: '6',
//     firstName:'Zainab',
//     lastName:'fatai ',
//     email: 'zainab@gmail.com',
//     username:'zainab',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/6.jpg',
//     phone: '123455678914',
//   },
//   {
//     id: '7',
//     firstName:'David',
//     lastName:'Johnson',
//     email: 'david@gmail.com',
//     username:'david',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/7.jpg',
//     phone: '123455678915',
//   },
//   {
//     id: '8',
//     firstName:'Mary',
//     lastName:'fatai Williams',
//     email: 'mary@gmail.com',
//     username:'mary',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/8.jpg',
//     phone: '123455678916',
//   },
//   {
//     id: '9',
//     firstName:'Ahmed',
//     lastName:'Sadiq',
//     email: 'ahmed@gmail.com',
//     username:'ahmed',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/9.jpg',
//     phone: '123455678917',
//   },
//   {
//     id: '10',
//     firstName:'Grace',
//     lastName:'Thompson',
//     email: 'grace@gmail.com',
//     username:'grace',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/10.jpg',
//     phone: '123455678918',
//   },
//   {
//     id: '11',
//     firstName:'Samuel',
//     lastName:'fatai ',
//     email: 'samuel@gmail.com',
//     username:'samuel',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/11.jpg',
//     phone: '123455678919',
//   },
//   {
//     id: '12',
//     firstName:'Linda',
//     lastName:'Carter',
//     email: 'linda@gmail.com',
//     username:'linda',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/12.jpg',
//     phone: '123455678920',
//   },
//   {
//     id: '13',
//     firstName:'Ibrahim',
//     lastName:'saheed ',
//     email: 'ibrahim@gmail.com',
//     username:'ibrahim',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/13.jpg',
//     phone: '123455678921',
//   },
//   {
//     id: '14',
//     firstName:'Sophia',
//     lastName:'fatai ',
//     email: 'sophia@gmail.com',
//     username:'sophia',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/14.jpg',
//     phone: '123455678922',
//   },
//   {
//     id: '15',
//     firstName:'Joseph',
//     lastName:'fatai ',
//     email: 'joseph@gmail.com',
//     username:'joseph',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/15.jpg',
//     phone: '123455678923',
//   },
//   {
//     id: '16',
//     firstName:'Hauwa',
//     lastName:'Mohammed',
//     email: 'hauwa@gmail.com',
//     username:'hauwa',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/16.jpg',
//     phone: '123455678924',
//   },
//   {
//     id: '17',
//     firstName:'Peter',
//     lastName:'Okoye',
//     email: 'peter@gmail.com',
//     username:'peter',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/17.jpg',
//     phone: '123455678925',
//   },
//   {
//     id: '18',
//     firstName:'Emily',
//     lastName:'White',
//     email: 'emily@gmail.com',
//     username:'emily',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/18.jpg',
//     phone: '123455678926',
//   },
//   {
//     id: '19',
//     firstName:'Abdul',
//     lastName:'Rahman',
//     email: 'abdul@gmail.com',
//     username:'abdul',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/19.jpg',
//     phone: '123455678927',
//   },
//   {
//     id: '20',
//     firstName:'Olivia',
//     lastName:'fatai ',
//     email: 'olivia@gmail.com',
//     username:'olivia',
//     sex:'MALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/women/20.jpg',
//     phone: '123455678928',
//   }
// ]
//     })

// const user = await prisma.student.create({
//     data: {
//     id: '1',
//     firstName:'Yunus',
//     lastName:'Fatai',
//     username :'yunus',
//      email: 'yunus@gmail.com',
//     sex:'FEMALE',
//     classId:1,
//     parentId:'fsnsbksfjksk',
//     gradeId:1,
//     bloodType:'O',
//     img: 'https://randomuser.me/api/portraits/men/1.jpg',
//     phone: '123455678909',
//   }
// })

// const grades = await prisma.grade.createMany({
//     data:[
//         {
//             id:1,
//             level:'45'
//         },
//         {
//             id:2,
//             level:'50'
//         },
//         {
//             id:3,
//             level:'90'
//         },
//         {
//             id:4,
//             level:'70'
//         },
//         {
//             id:5,
//             level:'100'
//         },
//     ]
// })

// classes

// const classes = await prisma.class.createMany({
//     data:
//    [
//     { name: "Class A1", capacity: 30, gradeId: 1, supervisorId: "1" },
//     { name: "Class A2", capacity: 28, gradeId: 1, supervisorId: "2" },
//     { name: "Class A3", capacity: 32, gradeId: 1, supervisorId: "3" },
//     { name: "Class A4", capacity: 25, gradeId: 1, supervisorId: "4" },

//     { name: "Class B1", capacity: 30, gradeId: 2, supervisorId: "5" },
//     { name: "Class B2", capacity: 29, gradeId: 2, supervisorId: "6" },
//     { name: "Class B3", capacity: 31, gradeId: 2, supervisorId: "7" },
//     { name: "Class B4", capacity: 27, gradeId: 2, supervisorId: "8" },

//     { name: "Class C1", capacity: 35, gradeId: 3, supervisorId: "9" },
//     { name: "Class C2", capacity: 33, gradeId: 3, supervisorId: "10" },
//     { name: "Class C3", capacity: 30, gradeId: 3, supervisorId: "11" },
//     { name: "Class C4", capacity: 28, gradeId: 3, supervisorId: "12" },

//     { name: "Class D1", capacity: 40, gradeId: 4, supervisorId: "13" },
//     { name: "Class D2", capacity: 36, gradeId: 4, supervisorId: "14" },
//     { name: "Class D3", capacity: 34, gradeId: 4, supervisorId: "15" },
//     { name: "Class D4", capacity: 32, gradeId: 4, supervisorId: "16" },

//     { name: "Class E1", capacity: 45, gradeId: 5, supervisorId: "17" },
//     { name: "Class E2", capacity: 42, gradeId: 5, supervisorId: "18" },
//     { name: "Class E3", capacity: 40, gradeId: 5, supervisorId: "19" },
//     { name: "Class E4", capacity: 38, gradeId: 5, supervisorId: "20" },
//   ],
// });


// const subject = await prisma.subject.createMany({
//   data: [
//     { name: "Mathematics", teacherId: "1" },
//     { name: "English Language", teacherId: "2" },
//     { name: "Physics", teacherId: "3" },
//     { name: "Chemistry", teacherId: "4" },
//     { name: "Biology", teacherId: "5" },

//     { name: "Further Mathematics", teacherId: "6" },
//     { name: "Literature", teacherId: "7" },
//     { name: "Government", teacherId: "8" },
//     { name: "Economics", teacherId: "9" },
//     { name: "Geography", teacherId: "10" },

//     { name: "Agricultural Science", teacherId: "1" },
//     { name: "Civic Education", teacherId: "2" },
//     { name: "Computer Science", teacherId: "3" },
//     { name: "Data Processing", teacherId: "4" },
//     { name: "Basic Technology", teacherId: "5" },

//     { name: "Business Studies", teacherId: "6" },
//     { name: "Accounting", teacherId: "7" },
//     { name: "Commerce", teacherId: "8" },
//     { name: "Marketing", teacherId: "9" },
//     { name: "Entrepreneurship", teacherId: "10" },
//   ],
// });


// const parents = await prisma.parent.createMany({
//   data: [
//     {
//       id: "1",
//       username: "parent1",
//       firstName: "John",
//       lastName: "Adeyemi",
//       email: "john.adeyemi@gmail.com",
//       phone: "08030000001",
//       address: "Ikeja, Lagos",
//       img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
//       sex: "MALE",
//     },
//     {
//       id: "2",
//       username: "parent2",
//       firstName: "Mary",
//       lastName: "Okafor",
//       email: "mary.okafor@gmail.com",
//       phone: "08030000002",
//       address: "Awka, Anambra",
//       img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
//       sex: "FEMALE",
//     },
//     {
//       id: "3",
//       username: "parent3",
//       firstName: "Samuel",
//       lastName: "Balogun",
//       email: "samuel.balogun@gmail.com",
//       phone: "08030000003",
//       address: "Ibadan, Oyo",
//       img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
//       sex: "MALE",
//     },
//     {
//       id: "4",
//       username: "parent4",
//       firstName: "Grace",
//       lastName: "Ahmed",
//       email: "grace.ahmed@gmail.com",
//       phone: "08030000004",
//       address: "Ilorin, Kwara",
//       img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
//       sex: "FEMALE",
//     },
//     {
//       id: "5",
//       username: "parent5",
//       firstName: "David",
//       lastName: "Olatunji",
//       email: "david.olatunji@gmail.com",
//       phone: "08030000005",
//       address: "Akure, Ondo",
//       img: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
//       sex: "MALE",
//     },
//     {
//       id: "6",
//       username: "parent6",
//       firstName: "Ruth",
//       lastName: "Eze",
//       email: "ruth.eze@gmail.com",
//       phone: "08030000006",
//       address: "Enugu, Enugu",
//       img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
//       sex: "FEMALE",
//     },
//     {
//       id: "7",
//       username: "parent7",
//       firstName: "Michael",
//       lastName: "Sadiq",
//       email: "michael.sadiq@gmail.com",
//       phone: "08030000007",
//       address: "Minna, Niger",
//       img: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c",
//       sex: "MALE",
//     },
//     {
//       id: "8",
//       username: "parent8",
//       firstName: "Blessing",
//       lastName: "Onyekachi",
//       email: "blessing.onyekachi@gmail.com",
//       phone: "08030000008",
//       address: "Owerri, Imo",
//       img: "https://images.unsplash.com/photo-1546967191-fdfb13ed6b1e",
//       sex: "FEMALE",
//     },
//     {
//       id: "9",
//       username: "parent9",
//       firstName: "Ibrahim",
//       lastName: "Musa",
//       email: "ibrahim.musa@gmail.com",
//       phone: "08030000009",
//       address: "Zaria, Kaduna",
//       img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde",
//       sex: "MALE",
//     },
//     {
//       id: "10",
//       username: "parent10",
//       firstName: "Aisha",
//       lastName: "Lawal",
//       email: "aisha.lawal@gmail.com",
//       phone: "08030000010",
//       address: "Ogbomosho, Oyo",
//       img: "https://images.unsplash.com/photo-1554151228-14d9def656e4",
//       sex: "FEMALE",
//     },

//     // 11–20
//     {
//       id: "11",
//       username: "parent11",
//       firstName: "Peter",
//       lastName: "Okorie",
//       email: "peter.okorie@gmail.com",
//       phone: "08030000011",
//       address: "Umuahia, Abia",
//       img: "https://images.unsplash.com/photo-1552058544-f2b08422138a",
//       sex: "MALE",
//     },
//     {
//       id: "12",
//       username: "parent12",
//       firstName: "Esther",
//       lastName: "Adebayo",
//       email: "esther.adebayo@gmail.com",
//       phone: "08030000012",
//       address: "Osogbo, Osun",
//       img: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c",
//       sex: "FEMALE",
//     },
//     {
//       id: "13",
//       username: "parent13",
//       firstName: "Joseph",
//       lastName: "Yakubu",
//       email: "joseph.yakubu@gmail.com",
//       phone: "08030000013",
//       address: "Lokoja, Kogi",
//       img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
//       sex: "MALE",
//     },
//     {
//       id: "14",
//       username: "parent14",
//       firstName: "Hannah",
//       lastName: "Salami",
//       email: "hannah.salami@gmail.com",
//       phone: "08030000014",
//       address: "Offa, Kwara",
//       img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
//       sex: "FEMALE",
//     },
//     {
//       id: "15",
//       username: "parent15",
//       firstName: "Sule",
//       lastName: "Abdullahi",
//       email: "sule.abdullahi@gmail.com",
//       phone: "08030000015",
//       address: "Kano, Kano",
//       img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
//       sex: "MALE",
//     },
//     {
//       id: "16",
//       username: "parent16",
//       firstName: "Deborah",
//       lastName: "Williams",
//       email: "deborah.williams@gmail.com",
//       phone: "08030000016",
//       address: "Lekki, Lagos",
//       img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
//       sex: "FEMALE",
//     },
//     {
//       id: "17",
//       username: "parent17",
//       firstName: "Paul",
//       lastName: "Chukwu",
//       email: "paul.chukwu@gmail.com",
//       phone: "08030000017",
//       address: "Nsukka, Enugu",
//       img: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
//       sex: "MALE",
//     },
//     {
//       id: "18",
//       username: "parent18",
//       firstName: "Janet",
//       lastName: "Ogun",
//       email: "janet.ogun@gmail.com",
//       phone: "08030000018",
//       address: "Abeokuta, Ogun",
//       img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
//       sex: "FEMALE",
//     },
//     {
//       id: "19",
//       username: "parent19",
//       firstName: "Usman",
//       lastName: "Danladi",
//       email: "usman.danladi@gmail.com",
//       phone: "08030000019",
//       address: "Sokoto, Sokoto",
//       img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde",
//       sex: "MALE",
//     },
//     {
//       id: "20",
//       username: "parent20",
//       firstName: "Victoria",
//       lastName: "Ajayi",
//       email: "victoria.ajayi@gmail.com",
//       phone: "08030000020",
//       address: "Ado-Ekiti, Ekiti",
//       img: "https://images.unsplash.com/photo-1546967191-fdfb13ed6b1e",
//       sex: "FEMALE",
//     },
//   ],
// });


// const students = await prisma.student.createMany({
//   data: [
//     {
//       id: "1",
//       username: "student1",
//       firstName: "Yunus",
//       lastName: "Abdullateef",
//       email: "student1@mail.com",
//       phone: "09010000001",
//       sex: "MALE",
//       classId: 1,
//       gradeId: 1,
//       parentId: "1",
//     },
//     {
//       id: "2",
//       username: "student2",
//       firstName: "Aisha",
//       lastName: "Lawal",
//       email: "student2@mail.com",
//       phone: "09010000002",
//       sex: "FEMALE",
//       classId: 2,
//       gradeId: 1,
//       parentId: "2",
//     },
//     {
//       id: "3",
//       username: "student3",
//       firstName: "Ibrahim",
//       lastName: "Musa",
//       email: "student3@mail.com",
//       phone: "09010000003",
//       sex: "MALE",
//       classId: 3,
//       gradeId: 1,
//       parentId: "3",
//     },
//     {
//       id: "4",
//       username: "student4",
//       firstName: "Zainab",
//       lastName: "Ahmed",
//       email: "student4@mail.com",
//       phone: "09010000004",
//       sex: "FEMALE",
//       classId: 4,
//       gradeId: 1,
//       parentId: "4",
//     },

//     {
//       id: "5",
//       username: "student5",
//       firstName: "Samuel",
//       lastName: "Okorie",
//       email: "student5@mail.com",
//       phone: "09010000005",
//       sex: "MALE",
//       classId: 5,
//       gradeId: 2,
//       parentId: "5",
//     },
//     {
//       id: "6",
//       username: "student6",
//       firstName: "Blessing",
//       lastName: "Eze",
//       email: "student6@mail.com",
//       phone: "09010000006",
//       sex: "FEMALE",
//       classId: 6,
//       gradeId: 2,
//       parentId: "6",
//     },
//     {
//       id: "7",
//       username: "student7",
//       firstName: "David",
//       lastName: "Adebayo",
//       email: "student7@mail.com",
//       phone: "09010000007",
//       sex: "MALE",
//       classId: 7,
//       gradeId: 2,
//       parentId: "7",
//     },
//     {
//       id: "8",
//       username: "student8",
//       firstName: "Ruth",
//       lastName: "Ogun",
//       email: "student8@mail.com",
//       phone: "09010000008",
//       sex: "FEMALE",
//       classId: 8,
//       gradeId: 2,
//       parentId: "8",
//     },

//     {
//       id: "9",
//       username: "student9",
//       firstName: "Joseph",
//       lastName: "Yakubu",
//       email: "student9@mail.com",
//       phone: "09010000009",
//       sex: "MALE",
//       classId: 9,
//       gradeId: 3,
//       parentId: "9",
//     },
//     {
//       id: "10",
//       username: "student10",
//       firstName: "Hannah",
//       lastName: "Salami",
//       email: "student10@mail.com",
//       phone: "09010000010",
//       sex: "FEMALE",
//       classId: 10,
//       gradeId: 3,
//       parentId: "10",
//     },
//     {
//       id: "11",
//       username: "student11",
//       firstName: "Paul",
//       lastName: "Chukwu",
//       email: "student11@mail.com",
//       phone: "09010000011",
//       sex: "MALE",
//       classId: 1,
//       gradeId: 3,
//       parentId: "11",
//     },
//     {
//       id: "12",
//       username: "student12",
//       firstName: "Esther",
//       lastName: "Akinwale",
//       email: "student12@mail.com",
//       phone: "09010000012",
//       sex: "FEMALE",
//       classId: 2,
//       gradeId: 3,
//       parentId: "12",
//     },

//     {
//       id: "13",
//       username: "student13",
//       firstName: "Sule",
//       lastName: "Abdullahi",
//       email: "student13@mail.com",
//       phone: "09010000013",
//       sex: "MALE",
//       classId: 3,
//       gradeId: 4,
//       parentId: "13",
//     },
//     {
//       id: "14",
//       username: "student14",
//       firstName: "Janet",
//       lastName: "Williams",
//       email: "student14@mail.com",
//       phone: "09010000014",
//       sex: "FEMALE",
//       classId: 4,
//       gradeId: 4,
//       parentId: "14",
//     },
//     {
//       id: "15",
//       username: "student15",
//       firstName: "Usman",
//       lastName: "Danladi",
//       email: "student15@mail.com",
//       phone: "09010000015",
//       sex: "MALE",
//       classId: 5,
//       gradeId: 4,
//       parentId: "15",
//     },
//     {
//       id: "16",
//       username: "student16",
//       firstName: "Deborah",
//       lastName: "Ajayi",
//       email: "student16@mail.com",
//       phone: "09010000016",
//       sex: "FEMALE",
//       classId: 6,
//       gradeId: 4,
//       parentId: "16",
//     },

//     {
//       id: "17",
//       username: "student17",
//       firstName: "Peter",
//       lastName: "Okafor",
//       email: "student17@mail.com",
//       phone: "09010000017",
//       sex: "MALE",
//       classId: 7,
//       gradeId: 5,
//       parentId: "17",
//     },
//     {
//       id: "18",
//       username: "student18",
//       firstName: "Victoria",
//       lastName: "Olatunji",
//       email: "student18@mail.com",
//       phone: "09010000018",
//       sex: "FEMALE",
//       classId: 8,
//       gradeId: 5,
//       parentId: "18",
//     },
//     {
//       id: "19",
//       username: "student19",
//       firstName: "Michael",
//       lastName: "Sadiq",
//       email: "student19@mail.com",
//       phone: "09010000019",
//       sex: "MALE",
//       classId: 9,
//       gradeId: 5,
//       parentId: "19",
//     },
//     {
//       id: "20",
//       username: "student20",
//       firstName: "Grace",
//       lastName: "Onyekachi",
//       email: "student20@mail.com",
//       phone: "09010000020",
//       sex: "FEMALE",
//       classId: 10,
//       gradeId: 5,
//       parentId: "20",
//     },
//   ],
// });

// const subjects = await prisma.lesson.createMany({
//   data: [
//     {
//       startTime: new Date("2025-02-01T08:00:00"),
//       endTime: new Date("2025-02-01T09:00:00"),
//       subjectId: 1,
//       classId: 1,
//       teacherId: "1",
//     },
//     {
//       startTime: new Date("2025-02-01T09:00:00"),
//       endTime: new Date("2025-02-01T10:00:00"),
//       subjectId: 2,
//       classId: 2,
//       teacherId: "2",
//     },
//     {
//       startTime: new Date("2025-02-01T10:00:00"),
//       endTime: new Date("2025-02-01T11:00:00"),
//       subjectId: 3,
//       classId: 3,
//       teacherId: "3",
//     },
//     {
//       startTime: new Date("2025-02-01T11:00:00"),
//       endTime: new Date("2025-02-01T12:00:00"),
//       subjectId: 4,
//       classId: 4,
//       teacherId: "4",
//     },

//     {
//       startTime: new Date("2025-02-02T08:00:00"),
//       endTime: new Date("2025-02-02T09:00:00"),
//       subjectId: 5,
//       classId: 5,
//       teacherId: "5",
//     },
//     {
//       startTime: new Date("2025-02-02T09:00:00"),
//       endTime: new Date("2025-02-02T10:00:00"),
//       subjectId: 6,
//       classId: 6,
//       teacherId: "6",
//     },
//     {
//       startTime: new Date("2025-02-02T10:00:00"),
//       endTime: new Date("2025-02-02T11:00:00"),
//       subjectId: 7,
//       classId: 7,
//       teacherId: "7",
//     },
//     {
//       startTime: new Date("2025-02-02T11:00:00"),
//       endTime: new Date("2025-02-02T12:00:00"),
//       subjectId: 8,
//       classId: 8,
//       teacherId: "8",
//     },

//     {
//       startTime: new Date("2025-02-03T08:00:00"),
//       endTime: new Date("2025-02-03T09:00:00"),
//       subjectId: 9,
//       classId: 9,
//       teacherId: "9",
//     },
//     {
//       startTime: new Date("2025-02-03T09:00:00"),
//       endTime: new Date("2025-02-03T10:00:00"),
//       subjectId: 10,
//       classId: 10,
//       teacherId: "10",
//     },

//     {
//       startTime: new Date("2025-02-03T10:00:00"),
//       endTime: new Date("2025-02-03T11:00:00"),
//       subjectId: 11,
//       classId: 1,
//       teacherId: "1",
//     },
//     {
//       startTime: new Date("2025-02-03T11:00:00"),
//       endTime: new Date("2025-02-03T12:00:00"),
//       subjectId: 12,
//       classId: 2,
//       teacherId: "2",
//     },

//     {
//       startTime: new Date("2025-02-04T08:00:00"),
//       endTime: new Date("2025-02-04T09:00:00"),
//       subjectId: 13,
//       classId: 3,
//       teacherId: "3",
//     },
//     {
//       startTime: new Date("2025-02-04T09:00:00"),
//       endTime: new Date("2025-02-04T10:00:00"),
//       subjectId: 14,
//       classId: 4,
//       teacherId: "4",
//     },
//     {
//       startTime: new Date("2025-02-04T10:00:00"),
//       endTime: new Date("2025-02-04T11:00:00"),
//       subjectId: 15,
//       classId: 5,
//       teacherId: "5",
//     },
//     {
//       startTime: new Date("2025-02-04T11:00:00"),
//       endTime: new Date("2025-02-04T12:00:00"),
//       subjectId: 16,
//       classId: 6,
//       teacherId: "6",
//     },

//     {
//       startTime: new Date("2025-02-05T08:00:00"),
//       endTime: new Date("2025-02-05T09:00:00"),
//       subjectId: 17,
//       classId: 7,
//       teacherId: "7",
//     },
//     {
//       startTime: new Date("2025-02-05T09:00:00"),
//       endTime: new Date("2025-02-05T10:00:00"),
//       subjectId: 18,
//       classId: 8,
//       teacherId: "8",
//     },
//     {
//       startTime: new Date("2025-02-05T10:00:00"),
//       endTime: new Date("2025-02-05T11:00:00"),
//       subjectId: 19,
//       classId: 9,
//       teacherId: "9",
//     },
//     {
//       startTime: new Date("2025-02-05T11:00:00"),
//       endTime: new Date("2025-02-05T12:00:00"),
//       subjectId: 20,
//       classId: 10,
//       teacherId: "10",
//     },
//   ],
// });


// const assignment = await prisma.assignment.createMany({
//   data: [
//     {
//       title: "Math Homework 1",
//       startDay: new Date("2025-02-01"),
//       endDay: new Date("2025-02-05"),
//       lessonId: 1,
//     },
//     {
//       title: "English Essay",
//       startDay: new Date("2025-02-02"),
//       endDay: new Date("2025-02-06"),
//       lessonId: 2,
//     },
//     {
//       title: "Physics Worksheet",
//       startDay: new Date("2025-02-03"),
//       endDay: new Date("2025-02-07"),
//       lessonId: 3,
//     },
//     {
//       title: "Chemistry Questions",
//       startDay: new Date("2025-02-04"),
//       endDay: new Date("2025-02-08"),
//       lessonId: 4,
//     },
//     {
//       title: "Biology Report",
//       startDay: new Date("2025-02-05"),
//       endDay: new Date("2025-02-09"),
//       lessonId: 5,
//     },
//     {
//       title: "History Assignment",
//       startDay: new Date("2025-02-06"),
//       endDay: new Date("2025-02-10"),
//       lessonId: 6,
//     },
//     {
//       title: "Geography Map Work",
//       startDay: new Date("2025-02-07"),
//       endDay: new Date("2025-02-11"),
//       lessonId: 7,
//     },
//     {
//       title: "Civic Education Task",
//       startDay: new Date("2025-02-08"),
//       endDay: new Date("2025-02-12"),
//       lessonId: 8,
//     },
//     {
//       title: "Computer Studies Practical",
//       startDay: new Date("2025-02-09"),
//       endDay: new Date("2025-02-13"),
//       lessonId: 9,
//     },
//     {
//       title: "Economics Homework",
//       startDay: new Date("2025-02-10"),
//       endDay: new Date("2025-02-14"),
//       lessonId: 10,
//     },

//     {
//       title: "Mathematics Revision",
//       startDay: new Date("2025-02-11"),
//       endDay: new Date("2025-02-15"),
//       lessonId: 11,
//     },
//     {
//       title: "Literature Review",
//       startDay: new Date("2025-02-12"),
//       endDay: new Date("2025-02-16"),
//       lessonId: 12,
//     },
//     {
//       title: "Physics Calculations",
//       startDay: new Date("2025-02-13"),
//       endDay: new Date("2025-02-17"),
//       lessonId: 13,
//     },
//     {
//       title: "Organic Chemistry Task",
//       startDay: new Date("2025-02-14"),
//       endDay: new Date("2025-02-18"),
//       lessonId: 14,
//     },
//     {
//       title: "Human Anatomy Notes",
//       startDay: new Date("2025-02-15"),
//       endDay: new Date("2025-02-19"),
//       lessonId: 15,
//     },
//     {
//       title: "World History Essay",
//       startDay: new Date("2025-02-16"),
//       endDay: new Date("2025-02-20"),
//       lessonId: 16,
//     },
//     {
//       title: "Climate Change Project",
//       startDay: new Date("2025-02-17"),
//       endDay: new Date("2025-02-21"),
//       lessonId: 17,
//     },
//     {
//       title: "Government Case Study",
//       startDay: new Date("2025-02-18"),
//       endDay: new Date("2025-02-22"),
//       lessonId: 18,
//     },
//     {
//       title: "Web Development Task",
//       startDay: new Date("2025-02-19"),
//       endDay: new Date("2025-02-23"),
//       lessonId: 19,
//     },
//     {
//       title: "Microeconomics Exercise",
//       startDay: new Date("2025-02-20"),
//       endDay: new Date("2025-02-24"),
//       lessonId: 20,
//     },
//   ],
// });


// const exams = await prisma.exam.createMany({
//   data: [
//     {
//       title: "Mathematics Midterm",
//       startTime: new Date("2025-03-01T09:00:00"),
//       endTime: new Date("2025-03-01T11:00:00"),
//       lessonId: 1,
//     },
//     {
//       title: "English Language Test",
//       startTime: new Date("2025-03-02T09:00:00"),
//       endTime: new Date("2025-03-02T11:00:00"),
//       lessonId: 2,
//     },
//     {
//       title: "Physics Assessment",
//       startTime: new Date("2025-03-03T10:00:00"),
//       endTime: new Date("2025-03-03T12:00:00"),
//       lessonId: 3,
//     },
//     {
//       title: "Chemistry Practical",
//       startTime: new Date("2025-03-04T09:00:00"),
//       endTime: new Date("2025-03-04T11:00:00"),
//       lessonId: 4,
//     },
//     {
//       title: "Biology Test",
//       startTime: new Date("2025-03-05T10:00:00"),
//       endTime: new Date("2025-03-05T12:00:00"),
//       lessonId: 5,
//     },
//     {
//       title: "History Examination",
//       startTime: new Date("2025-03-06T09:00:00"),
//       endTime: new Date("2025-03-06T11:00:00"),
//       lessonId: 6,
//     },
//     {
//       title: "Geography Quiz",
//       startTime: new Date("2025-03-07T10:00:00"),
//       endTime: new Date("2025-03-07T12:00:00"),
//       lessonId: 7,
//     },
//     {
//       title: "Civic Education Test",
//       startTime: new Date("2025-03-08T09:00:00"),
//       endTime: new Date("2025-03-08T11:00:00"),
//       lessonId: 8,
//     },
//     {
//       title: "Computer Studies Exam",
//       startTime: new Date("2025-03-09T10:00:00"),
//       endTime: new Date("2025-03-09T12:00:00"),
//       lessonId: 9,
//     },
//     {
//       title: "Economics Midterm",
//       startTime: new Date("2025-03-10T09:00:00"),
//       endTime: new Date("2025-03-10T11:00:00"),
//       lessonId: 10,
//     },

//     {
//       title: "Advanced Mathematics Test",
//       startTime: new Date("2025-03-11T09:00:00"),
//       endTime: new Date("2025-03-11T11:00:00"),
//       lessonId: 11,
//     },
//     {
//       title: "Literature Exam",
//       startTime: new Date("2025-03-12T10:00:00"),
//       endTime: new Date("2025-03-12T12:00:00"),
//       lessonId: 12,
//     },
//     {
//       title: "Physics Final",
//       startTime: new Date("2025-03-13T09:00:00"),
//       endTime: new Date("2025-03-13T11:00:00"),
//       lessonId: 13,
//     },
//     {
//       title: "Organic Chemistry Exam",
//       startTime: new Date("2025-03-14T10:00:00"),
//       endTime: new Date("2025-03-14T12:00:00"),
//       lessonId: 14,
//     },
//     {
//       title: "Human Biology Test",
//       startTime: new Date("2025-03-15T09:00:00"),
//       endTime: new Date("2025-03-15T11:00:00"),
//       lessonId: 15,
//     },
//     {
//       title: "World History Test",
//       startTime: new Date("2025-03-16T10:00:00"),
//       endTime: new Date("2025-03-16T12:00:00"),
//       lessonId: 16,
//     },
//     {
//       title: "Environmental Studies Exam",
//       startTime: new Date("2025-03-17T09:00:00"),
//       endTime: new Date("2025-03-17T11:00:00"),
//       lessonId: 17,
//     },
//     {
//       title: "Government Exam",
//       startTime: new Date("2025-03-18T10:00:00"),
//       endTime: new Date("2025-03-18T12:00:00"),
//       lessonId: 18,
//     },
//     {
//       title: "Software Development Test",
//       startTime: new Date("2025-03-19T09:00:00"),
//       endTime: new Date("2025-03-19T11:00:00"),
//       lessonId: 19,
//     },
//     {
//       title: "Microeconomics Final",
//       startTime: new Date("2025-03-20T10:00:00"),
//       endTime: new Date("2025-03-20T12:00:00"),
//       lessonId: 20,
//     },
//   ],
// });


// const events = await prisma.event.createMany({
//   data: [
//     {
//       title: "School Resumption",
//       description: "Official resumption for the new academic term",
//       startTime: new Date("2025-01-10T08:00:00"),
//       endTime: new Date("2025-01-10T10:00:00"),
//       classId: null,
//     },
//     {
//       title: "Class 1 Orientation",
//       description: "Orientation program for new students",
//       startTime: new Date("2025-01-12T09:00:00"),
//       endTime: new Date("2025-01-12T11:00:00"),
//       classId: 1,
//     },
//     {
//       title: "Class 2 Orientation",
//       description: "Introduction and briefing for Class 2 students",
//       startTime: new Date("2025-01-13T09:00:00"),
//       endTime: new Date("2025-01-13T11:00:00"),
//       classId: 2,
//     },
//     {
//       title: "Inter-House Sports",
//       description: "Annual inter-house sports competition",
//       startTime: new Date("2025-02-01T08:00:00"),
//       endTime: new Date("2025-02-01T16:00:00"),
//       classId: null,
//     },
//     {
//       title: "Class 3 Debate",
//       description: "Debate competition for Class 3",
//       startTime: new Date("2025-02-05T10:00:00"),
//       endTime: new Date("2025-02-05T12:00:00"),
//       classId: 3,
//     },
//     {
//       title: "Science Fair",
//       description: "School-wide science and innovation exhibition",
//       startTime: new Date("2025-02-10T09:00:00"),
//       endTime: new Date("2025-02-10T15:00:00"),
//       classId: null,
//     },
//     {
//       title: "Class 4 Quiz",
//       description: "Academic quiz competition for Class 4",
//       startTime: new Date("2025-02-12T10:00:00"),
//       endTime: new Date("2025-02-12T12:00:00"),
//       classId: 4,
//     },
//     {
//       title: "Teachers Meeting",
//       description: "General staff and teachers meeting",
//       startTime: new Date("2025-02-15T13:00:00"),
//       endTime: new Date("2025-02-15T15:00:00"),
//       classId: null,
//     },
//     {
//       title: "Class 5 Career Talk",
//       description: "Career guidance seminar for Class 5 students",
//       startTime: new Date("2025-02-18T10:00:00"),
//       endTime: new Date("2025-02-18T12:00:00"),
//       classId: 5,
//     },
//     {
//       title: "Cultural Day",
//       description: "Celebration of cultural diversity",
//       startTime: new Date("2025-02-22T09:00:00"),
//       endTime: new Date("2025-02-22T14:00:00"),
//       classId: null,
//     },

//     {
//       title: "Class 6 Workshop",
//       description: "Skill development workshop for Class 6",
//       startTime: new Date("2025-03-01T10:00:00"),
//       endTime: new Date("2025-03-01T13:00:00"),
//       classId: 6,
//     },
//     {
//       title: "Class 7 Leadership Training",
//       description: "Leadership training program for Class 7",
//       startTime: new Date("2025-03-03T09:00:00"),
//       endTime: new Date("2025-03-03T12:00:00"),
//       classId: 7,
//     },
//     {
//       title: "Mid-Term Break",
//       description: "Short academic break for all students",
//       startTime: new Date("2025-03-08T00:00:00"),
//       endTime: new Date("2025-03-10T23:59:00"),
//       classId: null,
//     },
//     {
//       title: "Class 8 Seminar",
//       description: "Educational seminar for Class 8",
//       startTime: new Date("2025-03-12T10:00:00"),
//       endTime: new Date("2025-03-12T12:00:00"),
//       classId: 8,
//     },
//     {
//       title: "Class 9 Revision Session",
//       description: "Revision class ahead of examinations",
//       startTime: new Date("2025-03-15T09:00:00"),
//       endTime: new Date("2025-03-15T12:00:00"),
//       classId: 9,
//     },
//     {
//       title: "Parents-Teachers Meeting",
//       description: "Meeting between parents and teachers",
//       startTime: new Date("2025-03-18T10:00:00"),
//       endTime: new Date("2025-03-18T14:00:00"),
//       classId: null,
//     },
//     {
//       title: "Class 10 Exam Briefing",
//       description: "Pre-exam briefing for Class 10 students",
//       startTime: new Date("2025-03-20T09:00:00"),
//       endTime: new Date("2025-03-20T11:00:00"),
//       classId: 10,
//     },
//     {
//       title: "Graduation Rehearsal",
//       description: "Practice session for graduating students",
//       startTime: new Date("2025-03-22T10:00:00"),
//       endTime: new Date("2025-03-22T13:00:00"),
//       classId: null,
//     },
//     {
//       title: "Graduation Ceremony",
//       description: "Official graduation ceremony",
//       startTime: new Date("2025-03-25T09:00:00"),
//       endTime: new Date("2025-03-25T15:00:00"),
//       classId: null,
//     },
//     {
//       title: "End of Term Party",
//       description: "Celebration marking the end of the term",
//       startTime: new Date("2025-03-28T12:00:00"),
//       endTime: new Date("2025-03-28T16:00:00"),
//       classId: null,
//     },
//   ],
// });


// const attendance = await prisma.attendance.createMany({
//   data: [
//     { date: new Date("2025-02-01"), isPresent: true,  studentId: "1",  lessonId: 1 },
//     { date: new Date("2025-02-01"), isPresent: true,  studentId: "2",  lessonId: 2 },
//     { date: new Date("2025-02-02"), isPresent: false, studentId: "3",  lessonId: 3 },
//     { date: new Date("2025-02-02"), isPresent: true,  studentId: "4",  lessonId: 4 },
//     { date: new Date("2025-02-03"), isPresent: true,  studentId: "5",  lessonId: 5 },
//     { date: new Date("2025-02-03"), isPresent: false, studentId: "6",  lessonId: 6 },
//     { date: new Date("2025-02-04"), isPresent: true,  studentId: "7",  lessonId: 7 },
//     { date: new Date("2025-02-04"), isPresent: true,  studentId: "8",  lessonId: 8 },
//     { date: new Date("2025-02-05"), isPresent: false, studentId: "9",  lessonId: 9 },
//     { date: new Date("2025-02-05"), isPresent: true,  studentId: "10", lessonId: 10 },

//     { date: new Date("2025-02-06"), isPresent: true,  studentId: "11", lessonId: 11 },
//     { date: new Date("2025-02-06"), isPresent: false, studentId: "12", lessonId: 12 },
//     { date: new Date("2025-02-07"), isPresent: true,  studentId: "13", lessonId: 13 },
//     { date: new Date("2025-02-07"), isPresent: true,  studentId: "14", lessonId: 14 },
//     { date: new Date("2025-02-08"), isPresent: false, studentId: "15", lessonId: 15 },
//     { date: new Date("2025-02-08"), isPresent: true,  studentId: "16", lessonId: 16 },
//     { date: new Date("2025-02-09"), isPresent: true,  studentId: "17", lessonId: 17 },
//     { date: new Date("2025-02-09"), isPresent: false, studentId: "18", lessonId: 18 },
//     { date: new Date("2025-02-10"), isPresent: true,  studentId: "19", lessonId: 19 },
//     { date: new Date("2025-02-10"), isPresent: true,  studentId: "20", lessonId: 20 },
//   ],
// });


// const announcement = await prisma.announcement.createMany({
//   data: [
//     {
//       title: "School Resumption Notice",
//       description: "School resumes officially for all students this term.",
//       date: new Date("2025-01-10"),
//       classId: null,
//     },
//     {
//       title: "Class 1 Orientation",
//       description: "Orientation program for newly admitted Class 1 students.",
//       date: new Date("2025-01-12"),
//       classId: 1,
//     },
//     {
//       title: "Class 2 Orientation",
//       description: "Welcome orientation for Class 2 students.",
//       date: new Date("2025-01-13"),
//       classId: 2,
//     },
//     {
//       title: "Inter-House Sports",
//       description: "Annual inter-house sports competition begins this week.",
//       date: new Date("2025-02-01"),
//       classId: null,
//     },
//     {
//       title: "Class 3 Debate Competition",
//       description: "Debate competition scheduled for Class 3 students.",
//       date: new Date("2025-02-05"),
//       classId: 3,
//     },
//     {
//       title: "Science Fair Announcement",
//       description: "All students are invited to the annual science fair.",
//       date: new Date("2025-02-10"),
//       classId: null,
//     },
//     {
//       title: "Class 4 Quiz",
//       description: "Academic quiz competition for Class 4.",
//       date: new Date("2025-02-12"),
//       classId: 4,
//     },
//     {
//       title: "Staff Meeting",
//       description: "General meeting for all teachers and staff.",
//       date: new Date("2025-02-15"),
//       classId: null,
//     },
//     {
//       title: "Class 5 Career Talk",
//       description: "Career guidance session for Class 5 students.",
//       date: new Date("2025-02-18"),
//       classId: 5,
//     },
//     {
//       title: "Cultural Day",
//       description: "Celebration of cultural heritage across the school.",
//       date: new Date("2025-02-22"),
//       classId: null,
//     },

//     {
//       title: "Class 6 Workshop",
//       description: "Skill acquisition workshop for Class 6.",
//       date: new Date("2025-03-01"),
//       classId: 6,
//     },
//     {
//       title: "Class 7 Leadership Training",
//       description: "Leadership training program for Class 7 students.",
//       date: new Date("2025-03-03"),
//       classId: 7,
//     },
//     {
//       title: "Mid-Term Break",
//       description: "School will be closed for the mid-term break.",
//       date: new Date("2025-03-08"),
//       classId: null,
//     },
//     {
//       title: "Class 8 Seminar",
//       description: "Educational seminar scheduled for Class 8.",
//       date: new Date("2025-03-12"),
//       classId: 8,
//     },
//     {
//       title: "Class 9 Revision",
//       description: "Revision classes ahead of examinations.",
//       date: new Date("2025-03-15"),
//       classId: 9,
//     },
//     {
//       title: "Parents-Teachers Meeting",
//       description: "Parents are invited for the PTM session.",
//       date: new Date("2025-03-18"),
//       classId: null,
//     },
//     {
//       title: "Class 10 Exam Briefing",
//       description: "Important briefing ahead of final exams.",
//       date: new Date("2025-03-20"),
//       classId: 10,
//     },
//     {
//       title: "Graduation Rehearsal",
//       description: "Rehearsal session for graduating students.",
//       date: new Date("2025-03-22"),
//       classId: null,
//     },
//     {
//       title: "Graduation Ceremony",
//       description: "Official graduation ceremony for final year students.",
//       date: new Date("2025-03-25"),
//       classId: null,
//     },
//     {
//       title: "End of Term Notice",
//       description: "End of term and resumption date announcement.",
//       date: new Date("2025-03-28"),
//       classId: null,
//     },
//   ],
// });


//  const admins = await prisma.admin.createMany({
//     data: [
//       {
//         id: '1',
//         username: 'admin_john',
//       },
//       {
//         id: '2',
//         username: 'admin_sarah',
//       },
//       {
//         id: '3',
//         username: 'admin_michael',
//       },
//       {
//         id: '4',
//         username: 'admin_emma',
//       },
//       {
//         id: '5',
//         username: 'admin_david',
//       },
//     ]
// })
  return (
    <div>manual data</div>
  )
}

export default page