export let role = 'admin'

export const calendarEvents = [
  {
    title: 'Math',
    allDay: false,
    start: new Date(2026, 0, 25, 8, 0),
    end: new Date(2026, 0, 25, 9, 0),
  },
  {
    title: 'English',
    allDay: false,
    start: new Date(2026, 0, 25, 9, 0),
    end: new Date(2026, 0, 25, 10, 0),
  },
  {
    title: 'Physics',
    allDay: false,
    start: new Date(2026, 0, 25, 10, 0),
    end: new Date(2026, 0, 25, 11, 0),
  },
  {
    title: 'Biology',
    allDay: false,
    start: new Date(2026, 0, 25, 11, 0),
    end: new Date(2026, 0, 25, 12, 0),
  },
  {
    title: 'History',
    allDay: false,
    start: new Date(2026, 0, 25, 12, 0),
    end: new Date(2026, 0, 25, 13, 0),
  },
  {
    title: 'Chemistry',
    allDay: false,
    start: new Date(2026, 0, 29, 13, 0),
    end: new Date(2026, 0, 29, 14, 0),
  },
  {
    title: 'Math',
    allDay: false,
    start: new Date(2026, 0,  24, 8, 0),
    end: new Date(2026, 0,  24, 9, 0),
  },
  {
    title: 'English',
    allDay: false,
    start: new Date(2026, 0, 12, 9, 0),
    end: new Date(2026, 0, 12, 10, 0),
  },
  {
    title: 'Physics',
    allDay: false,
    start: new Date(2026, 7, 12, 10, 0),
    end: new Date(2026, 7, 12, 11, 0),
  },
  {
    title: 'Biology',
    allDay: false,
    start: new Date(2026, 7, 12, 11, 0),
    end: new Date(2026, 7, 12, 12, 0),
  },
  {
    title: 'History',
    allDay: false,
    start: new Date(2026, 7, 12, 12, 0),
    end: new Date(2026, 7, 12, 13, 0),
  },
  {
    title: 'Chemistry',
    allDay: false,
    start: new Date(2026, 7, 12, 13, 0),
    end: new Date(2026, 7, 12, 14, 0),
  },
  {
    title: 'Math',
    allDay: false,
    start: new Date(2026, 0, 22, 8, 0),
    end: new Date(2026, 0, 22, 9, 0),
  },
  {
    title: 'English',
    allDay: false,
    start: new Date(2026, 0, 23, 9, 0),
    end: new Date(2026, 0, 23, 10, 0),
  },
  {
    title: 'Physics',
    allDay: false,
    start: new Date(2026, 7, 12, 10, 0),
    end: new Date(2026, 7, 12, 11, 0),
  },
  {
    title: 'Biology',
    allDay: false,
    start: new Date(2026, 7, 12, 11, 0),
    end: new Date(2026, 7, 12, 12, 0),
  },
  {
    title: 'History',
    allDay: false,
    start: new Date(2026, 7, 12, 12, 0),
    end: new Date(2026, 7, 12, 13, 0),
  },
  {
    title: 'Chemistry',
    allDay: false,
    start: new Date(2026, 7, 12, 13, 0),
    end: new Date(2026, 7, 12, 14, 0),
  },
];

export const teacherData = [
  {
    id: 1,
    teacherId: 'T1001',
    name: 'Yunus Abdullateef',
    email: 'yunus@gmail.com',
    phone: '+2348012345671',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    subjects: ['Math', 'Geometry'],
    classes: ['1B', '2A', '3C'],
    address: '123 Main St, Anytown, USA',
  },
  {
    id: 2,
    teacherId: 'T1002',
    name: 'Amina Bello',
    email: 'amina@gmail.com',
    phone: '+2348012345672',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    subjects: ['English', 'Literature'],
    classes: ['1A', '2B'],
    address: '45 Unity Road, Lagos, Nigeria',
  },
  {
    id: 3,
    teacherId: 'T1003',
    name: 'David Okoye',
    email: 'david@gmail.com',
    phone: '+2348012345673',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    subjects: ['Physics', 'Math'],
    classes: ['3A', '4B'],
    address: '78 Palm Street, Abuja, Nigeria',
  },
  {
    id: 4,
    teacherId: 'T1004',
    name: 'Fatima Sule',
    email: 'fatima@gmail.com',
    phone: '+2348012345674',
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
    subjects: ['Biology', 'Chemistry'],
    classes: ['2C', '3B'],
    address: '12 School Lane, Ilorin, Nigeria',
  },
  {
    id: 5,
    teacherId: 'T1005',
    name: 'Michael Johnson',
    email: 'michael@gmail.com',
    phone: '+447911234561',
    photo: 'https://randomuser.me/api/portraits/men/5.jpg',
    subjects: ['History', 'Civic Education'],
    classes: ['1C', '2A'],
    address: '90 Green Ave, London, UK',
  },
  {
    id: 6,
    teacherId: 'T1006',
    name: 'Zainab Musa',
    email: 'zainab@gmail.com',
    phone: '+2348012345676',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
    subjects: ['Economics', 'Commerce'],
    classes: ['4A', '5B'],
    address: 'Kawo Street, Kaduna, Nigeria',
  },
  {
    id: 7,
    teacherId: 'T1007',
    name: 'Joseph Brown',
    email: 'joseph@gmail.com',
    phone: '+14161234567',
    photo: 'https://randomuser.me/api/portraits/men/7.jpg',
    subjects: ['Geography', 'Agriculture'],
    classes: ['2B', '3A'],
    address: 'Maple Road, Toronto, Canada',
  },
  {
    id: 8,
    teacherId: 'T1008',
    name: 'Halima Danjuma',
    email: 'halima@gmail.com',
    phone: '+2348012345678',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    subjects: ['Islamic Studies', 'Arabic'],
    classes: ['1A', '2C'],
    address: 'Emir Road, Zaria, Nigeria',
  },
  {
    id: 9,
    teacherId: 'T1009',
    name: 'Samuel Ade',
    email: 'samuel@gmail.com',
    phone: '+2348012345679',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    subjects: ['Computer', 'Data Processing'],
    classes: ['3C', '4A'],
    address: 'Akobo, Ibadan, Nigeria',
  },
  {
    id: 10,
    teacherId: 'T1010',
    name: 'Grace Williams',
    email: 'grace@gmail.com',
    phone: '+2348012345680',
    photo: 'https://randomuser.me/api/portraits/women/10.jpg',
    subjects: ['Government', 'Civic Education'],
    classes: ['2A', '3B'],
    address: 'Victoria Island, Lagos, Nigeria',
  },
  {
    id: 11,
    teacherId: 'T1011',
    name: 'Ibrahim Lawal',
    email: 'ibrahim@gmail.com',
    phone: '+2348012345681',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    subjects: ['Further Math', 'Physics'],
    classes: ['4B', '5A'],
    address: 'Oja Oba, Ilorin, Nigeria',
  },
  {
    id: 12,
    teacherId: 'T1012',
    name: 'Rita Martins',
    email: 'rita@gmail.com',
    phone: '+2348012345682',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    subjects: ['French', 'English'],
    classes: ['1B', '2C'],
    address: 'Yaba, Lagos, Nigeria',
  },
  {
    id: 13,
    teacherId: 'T1013',
    name: 'Abdul Kareem',
    email: 'abdul@gmail.com',
    phone: '+2348012345683',
    photo: 'https://randomuser.me/api/portraits/men/13.jpg',
    subjects: ['Chemistry', 'Basic Science'],
    classes: ['2B', '3C'],
    address: 'Ogbomosho, Oyo, Nigeria',
  },
  {
    id: 14,
    teacherId: 'T1014',
    name: 'Janet Cole',
    email: 'janet@gmail.com',
    phone: '+2348012345684',
    photo: 'https://randomuser.me/api/portraits/women/14.jpg',
    subjects: ['Home Economics', 'Food & Nutrition'],
    classes: ['1C', '2A'],
    address: 'Asokoro, Abuja, Nigeria',
  },
  {
    id: 15,
    teacherId: 'T1015',
    name: 'Musa Sadiq',
    email: 'musa@gmail.com',
    phone: '+2348012345685',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    subjects: ['Accounting', 'Business Studies'],
    classes: ['3A', '4C'],
    address: 'Minna, Niger, Nigeria',
  },
  {
    id: 16,
    teacherId: 'T1016',
    name: 'Linda Park',
    email: 'linda@gmail.com',
    phone: '+821012345678',
    photo: 'https://randomuser.me/api/portraits/women/16.jpg',
    subjects: ['Fine Art', 'Creative Arts'],
    classes: ['1A', '2B'],
    address: 'Seoul Street, South Korea',
  },
  {
    id: 17,
    teacherId: 'T1017',
    name: 'Sola Adebayo',
    email: 'sola@gmail.com',
    phone: '+2348012345687',
    photo: 'https://randomuser.me/api/portraits/men/17.jpg',
    subjects: ['Music', 'Cultural Arts'],
    classes: ['2C', '3A'],
    address: 'Ikeja, Lagos, Nigeria',
  },
  {
    id: 18,
    teacherId: 'T1018',
    name: 'Mary Thompson',
    email: 'mary@gmail.com',
    phone: '+447911234568',
    photo: 'https://randomuser.me/api/portraits/women/18.jpg',
    subjects: ['Health Education', 'Physical Education'],
    classes: ['1B', '2B'],
    address: 'Birmingham, UK',
  },
  {
    id: 19,
    teacherId: 'T1019',
    name: 'Umar Abdullahi',
    email: 'umar@gmail.com',
    phone: '+2348012345689',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    subjects: ['Geography', 'Environmental Studies'],
    classes: ['3B', '4A'],
    address: 'Sokoto, Nigeria',
  },
  {
    id: 20,
    teacherId: 'T1020',
    name: 'Patricia Young',
    email: 'patricia@gmail.com',
    phone: '+12125551234',
    photo: 'https://randomuser.me/api/portraits/women/20.jpg',
    subjects: ['Psychology', 'Guidance & Counseling'],
    classes: ['4C', '5A'],
    address: 'New York, USA',
  },
];
